SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `SUBD` ;
USE `SUBD` ;


CREATE TABLE IF NOT EXISTS `SUBD`.`SYNOPTIC` (
  `synopticID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`synopticID`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `SUBD`.`WEATHER` (
  `weatherID` INT NOT NULL AUTO_INCREMENT,
  `temperature` INT NOT NULL,
  `windSpeed` INT NULL,
  `windDirection` VARCHAR(10) NULL,
  `airHumidity` INT NULL,
  `UVindex` VARCHAR(45) NULL,
  PRIMARY KEY (`weatherID`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `SUBD`.`STATION` (
  `stationID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  PRIMARY KEY (`stationID`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `SUBD`.`WEATHER_IDENTIFIER` (
  `identifierID` INT NOT NULL AUTO_INCREMENT,
  `synopticID` INT NULL,
  `stationID` INT NULL,
  `weatherID` INT NULL,
  PRIMARY KEY (`identifierID`),
  CONSTRAINT `indentifier_station`
    FOREIGN KEY (stationID)
    REFERENCES `SUBD`.`STATION` (stationID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `indentifier_synoptic`
    FOREIGN KEY (synopticID)
    REFERENCES `SUBD`.`SYNOPTIC` (synopticID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `identifier_weather`
    FOREIGN KEY (weatherID)
    REFERENCES `SUBD`.`WEATHER` (weatherID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `SUBD`.`USERS` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `SUBD`.`LOCATION` (
  `locationID` INT NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`locationID`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `SUBD`.`REQUESTS` (
  `requestID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NULL,
  `locationID` INT NULL,
  `identifierID` INT NULL,
  PRIMARY KEY (`requestID`),
  CONSTRAINT `request_user`
    FOREIGN KEY (userID)
    REFERENCES `SUBD`.`USERS` (userID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `request_location`
    FOREIGN KEY (locationID)
    REFERENCES `SUBD`.`LOCATION` (locationID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `request_identifier`
    FOREIGN KEY (identifierID)
    REFERENCES `SUBD`.`WEATHER_IDENTIFIER` (identifierID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
